[bars.status]
modules_start = ["clock", "battery_status", "volume_status"]
modules_center = ["power_profiles", "mpris", "cpu"]
modules_end = ["tray", "power"]
anchors = ["right"]
orientation = "vertical"
separators = true
width = 90
height = "auto"

[bars.bar]
modules_start = ["sway"]
modules_end = ["volume", "battery"]
anchors = ["left", "top", "right"]
orientation = "horizontal"
exclusive = true

[modules.volume]
type = "volume"

[modules.clock]
type = "clock"

[modules.battery]
type = "battery"

[modules.power_profiles]
type = "power_profiles"

[modules.mpris]
type = "mpris"
show_label = true
label = "MPRIS"

[modules.cpu]
type = "cpu"
show_label = true
label = "CPU"

[modules.tray]
type = "tray"

[modules.power]
type = "power"

[modules.sway]
type = "sway"

[modules.battery_status]
type = "battery"
show_label = true
label = "Battery"

[modules.volume_status]
type = "volume"
show_label = true
label = "Volume"
